[versions]
# libraries
caffeine = "3.1.8"
datetime = "0.6.1"
junit = "4.13.2"
serialization = "1.7.3"
semver4j = "5.4.1"

# plugins
changelog = "2.2.1"
intellijPlatform = "2.1.0"
kotlin = "2.0.21"
kover = "0.8.3"
qodana = "2024.2.6"

[libraries]
caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffeine" }
datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
semver4j = { group = "org.semver4j", name = "semver4j", version.ref = "semver4j" }
serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intellijPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
serialization = { id = "plugin.serialization", version.ref = "kotlin" }
