[versions]
# libraries
semver4j = "5.3.0"
junit = "4.13.2"

# plugins
changelog = "2.2.1"
intellijPlatform = "2.0.0"
kotlin = "2.0.0"
serialization = "1.7.1"
kover = "0.8.3"
qodana = "2024.1.5"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
semver4j = { group = "org.semver4j", name = "semver4j", version.ref = "semver4j" }
serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intellijPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
serialization = { id = "plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
